name: Run the Action on each commit
on:
  push:
    branches:
      - 'main'
jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr create -B 'dev-elementum' -t 'Updating dev-elementum' -b 'This is a automatic PR'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

