name: Run the Action on each commit
on:
  push:
    branches:
      - 'main'
jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh pr create -B 'dev-elementum' -a 'nsolorzano16' -t 'Updating dev-elementum' -b 'This is a automatic PR '
        env:
          GH_TOKEN: ${{ github.token }}
      

